const imgList = [
    {name: "Australian Cattle Dog", 
        url: "https://images.unsplash.com/photo-1602431694956-0da68eb649b4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1232&q=80", 
        description: "Sometimes called a Blue Heeler, the Australian Cattle Dog is a herding dog originating in Australia."},
    {name: "Basset Hound", url: "", description: ""},
    {name: "Beagle", url: "", description: ""},
    {name: "Border Collie", url: "", description: ""},
    {name: "Boston Terrier", url: "", description: ""},
    {name: "Boxer", url: "", description: ""},
    {name: "Boykin Spaniel", url: "", description: ""},
    {name: "Bull Terrier", url: "", description: ""},
    {name: "Bulldog", url: "", description: ""},
    {name: "Cavalier King Charles Spaniel", url: "", description: ""},
    {name: "Chihuahua", url: "", description: ""},
    {name: "Dachshund", url: "", description: ""},
    {name: "Dalmation", url: "", description: ""},
    {name: "Doberman Pinscher", url: "", description: ""},
    {name: "German Shepherd", url: "", description: ""},
    {name: "Golden Retriever", url: "", description: ""},
    {name: "Great Dane", url: "", description: ""},
    {name: "Greyhound", url: "", description: ""},
    {name: "Irish Setter", url: "", description: ""},
    {name: "Jack Russell Terrier", url: "", description: ""},
    {name: "Labrador Retriever", url: "", description: ""},
    {name: "Maltese", url: "", description: ""},
    {name: "Miniature Pinscher", url: "", description: ""},
    {name: "Norwegian Elkhound", url: "", description: ""},
    {name: "Old English Sheepdog", url: "", description: ""},
    {name: "Pembroke Welsh Corgi", url: "", description: ""},
    {name: "Pharaoh Hound", url: "", description: ""},
    {name: "Pomeranian", url: "", description: ""},
    {name: "Poodle", url: "", description: ""},
    {name: "Portuguese Water Dog", url: "", description: ""},
    {name: "Pug", url: "", description: ""},
    {name: "Rat Terrier", url: "", description: ""},
    {name: "Rhodesian Ridgeback", url: "", description: ""},
    {name: "Rottweiler", url: "", description: ""},
    {name: "Samoyed", url: "", description: ""},
    {name: "Schipperke", url: "", description: ""},
    {name: "Scottish Terrier", url: "", description: ""},
    {name: "Shar Pei", url: "", description: ""},
    {name: "Shetland Sheepdog", url: "", description: ""},
    {name: "Shiba Inu", url: "", description: ""},
    {name: "Shih Tzu", url: "", description: ""},
    {name: "Siberian Husky", url: "", description: ""},
    {name: "Staffordshire Bull Terrier", url: "", description: ""},
    {name: "Teddy Roosevelt Terrier", url: "", description: ""},
    {name: "Tibetan Mastiff", url: "", description: ""},
    {name: "Treeing Walker Coonhound", url: "", description: ""},
    {name: "Weimaraner", url: "", description: ""},
    {name: "West Highland White Terrier", url: "", description: ""},
    {name: "Whippet", url: "", description: ""},
    {name: "Xoloitzcuintle", url: "", description: ""},
    {name: "Yorkshire Terrie", url: "", description: ""}
];

export default imgList